DLL_NAME = libspirv-cross-c-shared.dll
CMAKE_OPTIONS =\
-DSPIRV_CROSS_SHARED=ON\
-DSPIRV_CROSS_STATIC=OFF\
-DSPIRV_CROSS_CLI=OFF\
-DSPIRV_CROSS_ENABLE_TESTS=OFF\
-DSPIRV_CROSS_ENABLE_MSL=OFF\
-DSPIRV_CROSS_ENABLE_CPP=OFF\
-DSPIRV_CROSS_ENABLE_REFLECT=OFF\
-DSPIRV_CROSS_ENABLE_UTIL=OFF\
-DCMAKE_CXX_FLAGS=-D__USE_MINGW_ANSI_STDIO\
-DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=ON

include Prelude.mk
