DLL_NAME = libspirv-cross-c-shared.dll

include Prelude.mk

$(BIN_DLL): $(PKG_BUILD) FORCE
	$(SUB_NINJA)
	$(SUB_NINJA) install

$(PKG_BUILD):
	cmake -H$(PKG_SRC) -B$(PKG_BUILD) -GNinja\
		-DCMAKE_INSTALL_PREFIX=$(PREFIX)\
		-DCMAKE_BUILD_TYPE=Release\
		-DCMAKE_TOOLCHAIN_FILE=$(SRC)/toolchain.cmake\
		-DSPIRV_CROSS_SHARED=ON\
		-DSPIRV_CROSS_STATIC=OFF\
		-DSPIRV_CROSS_CLI=OFF\
		-DSPIRV_CROSS_ENABLE_TESTS=OFF\
		-DSPIRV_CROSS_ENABLE_MSL=OFF\
		-DSPIRV_CROSS_ENABLE_CPP=OFF\
		-DSPIRV_CROSS_ENABLE_REFLECT=OFF\
		-DSPIRV_CROSS_ENABLE_UTIL=OFF\
		-DCMAKE_CXX_FLAGS=-D__USE_MINGW_ANSI_STDIO\
		-DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=ON

clean:
	$(SUB_NINJA) clean

distclean:
	rm -rf $(PKG_BUILD)
