name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Show system info
      run: sudo apt install neofetch && neofetch

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install prerequisites
      run: sudo make apt-install

    - name: Make
      run: make

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*
